# Generated by Django 3.0.1 on 2020-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='sub_sub_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='short_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
